version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Mount Docker socket for Docker-outside-of-Docker
      - ./data:/app/data # Persist application data (db.json)
    env_file:
      - ./.env
    restart: unless-stopped
